version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules


